USE ROLE USERADMIN;

SELECT current_role(); -- chek the role

SELECT current_user(); -- check the user

CREATE ROLE AUTO_READER; -- create a new role 
-- DROP ROLE <WRITE THE ROLE HERE>

CREATE ROLE AUTO_WRITER COMMENT
= "Able to do CRUD operations on auto database"; 

CREATE ROLE AUTO_ANALYST COMMENT
= "Able to create views on auto_database";



USE ROLE SECURITYADMIN; -- changed the role to set and grant
GRANT USAGE ON WAREHOUSE dw TO ROLE AUTO_READER; -- SET GRANTS
GRANT USAGE ON DATABASE auto_db TO ROLE AUTO_READER;

SHOW GRANTS TO ROLE AUTO_READER;

GRANT USAGE ON ALL SCHEMAS IN DATABASE AUTO_DB TO ROLE AUTO_READER; -- allows to work with all schemas

GRANT SELECT ON ALL TABLES IN SCHEMA AUTO_DB.PUBLIC TO ROLE AUTO_READER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA AUTO_DB.PUBLIC TO ROLE AUTO_READER; -- all futures tables that are created in this schema public for the SELECT privilege

SHOW FUTURE GRANTS IN SCHEMA AUTO_DB.PUBLIC;

GRANT ROLE AUTO_READER TO ROLE AUTO_WRITER; -- READET GIVES GRANT TO WRITER

SHOW GRANTS TO ROLE AUTO_WRITER;

GRANT INSERT,
UPDATE,
DELETE ON ALL TABLES IN SCHEMA auto_db.public TO ROLE AUTO_WRITER;

GRANT INSERT,
UPDATE,
DELETE ON FUTURE TABLES IN SCHEMA auto_db.public TO ROLE AUTO_WRITER;

GRANT CREATE TABLE ON SCHEMA auto_db.public TO ROLE auto_writer;
SHOW FUTURE GRANTS IN SCHEMA auto_db.public; -- to see the privileges

SHOW GRANTS TO ROLE auto_writer;


GRANT ROLE AUTO_WRITER TO USER Dimitris;

USE ROLE AUTO_WRITER;